title: "Pari Vermani"
description: "Building AI-driven products for real-world decision-making and operational efficiency"

minimal_mistakes_skin: "default"

url: "https://parivermani.github.io"
baseurl: ""

author:
name: "Pari Vermani"

markdown: kramdown